name: Preconditions

description: Checkout and install required software

inputs:
  python_version:
    description: "The Python version to use"
    required: false
    default: "3.12"
  poetry_version:
    description: "The Poetry version to use"
    required: false
    default: "2.1.3"

runs:
  using: "composite"
  steps:

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install Poetry
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install "poetry==${{ inputs.poetry_version }}"
