name: Preconditions

description: Checkout and install required software

inputs:
  python_version:
    description: "The Python version to use"
    required: false
    default: "3.14"
  uv_version:
    description: "The uv version to use"
    required: false
    default: "0.8.14"

runs:
  using: "composite"
  steps:

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: ${{ inputs.uv_version }}
        enable-cache: true

    - name: Install dependencies
      shell: bash
      run: uv sync --frozen
