name: Build and Push Docker Image

description: Builds and pushes the Docker image to the GitHub Container Registry.

inputs:
  mlflow_version:
    description: "The mlflow version to tag the image with"
    required: true
  mlflow_oidc_version:
    description: "The mlflow-oidc version to tag the image with"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate date tag
      id: generate_date
      shell: bash
      run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/mlflow-tracking-server:latest
          ghcr.io/${{ github.repository_owner }}/mlflow-tracking-server:${{ inputs.mlflow_version }}-${{ inputs.mlflow_oidc_version }}-${{ steps.generate_date.outputs.date }}
