name: Update Versions

description: Updates the versions in pyproject.toml and rebuilds the lock file.

inputs:
  mlflow_version:
    description: "The latest mlflow version"
    required: true
  mlflow_oidc_version:
    description: "The latest mlflow-oidc version"
    required: true

runs:
  using: "composite"
  steps:

    - name: Update dependencies
      shell: bash
      run: |
        uv add 'mlflow-oidc-auth[caching-redis,fastapi,full]==${{ inputs.mlflow_oidc_version }}'
        uv add 'mlflow[genai]==${{ inputs.mlflow_version }}'

    - name: Rebuild lock file
      shell: bash
      run: uv lock

    - name: Commit and push changes
      shell: bash
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        git add pyproject.toml
        git add uv.lock

        git commit -m "feat: rebuild image for mlflow ${{ inputs.mlflow_version }} and mlflow-oidc ${{ inputs.mlflow_oidc_version }}"
        git push
