name: Docker Image Release

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check versions
        id: check_versions
        uses: ./.github/actions/check-versions.yaml

      - name: Update versions
        if: ${{ steps.check_versions.outputs.versions_changed == 'true' }}
        uses: ./.github/actions/update-versions.yaml
        with:
          mlflow_version: ${{ steps.check_versions.outputs.mlflow_version }}
          mlflow_oidc_version: ${{ steps.check_versions.outputs.mlflow_oidc_version }}

      - name: Build and push Docker image
        if: ${{ steps.check_versions.outputs.versions_changed == 'true' }} || github.event_name == 'workflow_dispatch' }}
        uses: ./.github/actions/build-and-push.yaml
        with:
          mlflow_version: ${{ steps.check_versions.outputs.mlflow_version }}
          mlflow_oidc_version: ${{ steps.check_versions.outputs.mlflow_oidc_version }}
